### ISSUE TITLE
Unable to create wordlist directory on first setup

### ISSUE THREAD

**Issue by puzzlepeaches** [puzzlepeaches/ffufw#3]
If `~/.ffufw/wordlists` does not already exist, the tool fails to create it for wordlist downloading.

https://github.com/puzzlepeaches/ffufw/blob/d5ad9749fff7f15da6d2766b9c4f334edeef816c/cmd/wordlists/setup.go#L39C1-L39C1

**Comment by vysecurity** [comment]
`mkdir ~/.ffufw`

**Comment by puzzlepeaches** [comment]
Resolved by https://github.com/puzzlepeaches/ffufw/commit/cfd48b6e7583682498e9869670008503f83f0c80
