### ISSUE TITLE
Ability to turn dictionaries off/on

### ISSUE THREAD

**Issue by nullenc0de** [puzzlepeaches/ffufw#7]
I know it doesn't support custom dictionaries. But it would be nice if there was a way to toggle dictionaries on and off. i.e. the user has a list of endpoints they want to validate/postprocess. 

sample:
ffufw -i endpoints.txt -wordlist off -o out

**Comment by puzzlepeaches** [comment]
Added support in latest commit. Let me know if you run into any issues @nullenc0de!
