### ISSUE TITLE
Error on first run

### ISSUE THREAD

**Issue by BuffaloWill** [puzzlepeaches/ffufw#8]
When running ffufw for the first time, I received errors like the following:

```
...
DEBU[0001] Running command: /root/go/bin/ffuf -u https://[TARGET]/FUZZ -config /root/.ffufrc -w /root/.ffufw/wordlists/misc/raft-medium-files.txt -of json -od out/https_8541-TARGET -o out/https_8541-TARGET/results.raft-medium-files.json
ERRO[0001] Error running FFUF: exit status 1 [URL: https://8541-TARGET]
....
````

Digging further showed the following error from ffuf:

```
Encoutered error(s): open /root/.ffufrc: no such file or directory
```

Creating an empty /root/.ffufrc (`touch /root/.ffufrc`) fixed the issue for me. 

This was the command I was using:
```
ffufw -i ./targets.txt -o ./out -v
```

**Comment by Hackndo** [comment]
I had the same issue, this fixed it. Thanks

**Comment by Teicu** [comment]
same issue here, how to fix it in mac os? thx

**Comment by puzzlepeaches** [comment]
Fixed by https://github.com/puzzlepeaches/ffufw/commit/8768b1c4fbf0c8ab2f781c9b5de269eb28eb56af
